version: '3.8'

services:
  # 1. Aplikasi Backend Kita
  backend:
    build: .
    container_name: umkm-backend-app
    ports:
      - "8000:7860"
    env_file:
      - .env
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 7860 --reload
    depends_on:
      - db  # Tunggu database nyala dulu baru backend jalan
    networks:
      - umkm-network

  # 2. Database MySQL Local (Wadah Baru)
  db:
    image: mysql:8.0
    container_name: umkm-db-local
    restart: always
    environment:
      MYSQL_DATABASE: umkm_db_local
      MYSQL_USER: user_local
      MYSQL_PASSWORD: password_local
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306" # Port 3307 di laptop, 3306 di container (biar gak bentrok kalau ada mysql lain)
    volumes:
      - mysql_data:/var/lib/mysql # Simpan data biar gak hilang pas restart
    networks:
      - umkm-network
  
  frontend:
    build: ../frontend         
    container_name: umkm-frontend-app
    ports:
      - "5173:5173"            
    volumes:
      - ../frontend:/app       
      - /app/node_modules      
    depends_on:
      - backend                
    networks:
      - umkm-network

# Setup Network & Volume
networks:
  umkm-network:
    driver: bridge

volumes:
  mysql_data: